format = """
[  ](fg:blue)\
$directory\
$git_branch\
$git_status\
$php\
$nodejs\
$rust\
$python\
\n$character"""

[directory]
format = "[$path](fg:bright-black)"
truncation_length = 3
truncation_symbol = "/"

[git_branch]
symbol = " "
format = ' [$symbol](fg:red) [$branch](fg:bright-black)'

[git_status]
format = '[$all_status$ahead_behind](fg:bright-black)'

[nodejs]
symbol = " "
format = ' [$symbol](fg:red) [$version](fg:bright-black)'

[rust]
symbol = " "
format = ' [$symbol](fg:purple) [$version](fg:bright-black)'

[python]
symbol = " "
format = ' [$symbol](fg:cyan) [$version $virtualenv](fg:bright-black)'

[php]
symbol = " "
format = ' [$symbol](fg:blue) [$version](fg:bright-black)'
